default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  timeout: 5000
  username: <%= ENV["HELLO_USERNAME"] %>
  password: <%= ENV["HELLO_PASSWORD"] %>

development:
  <<: *default
  database: rails_backend_dev

test:
  <<: *default
  database: rails_backend_test

production:
  <<: *default
  database: rails_backend_prod
